exclude: ".*snap$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [pem]
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.2"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        name: Prettier
        entry: prettier --write --ignore-unknown
        additional_dependencies:
          - prettier@3.2.5
